name: binutils-cil CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: apt-get update
      run: sudo apt-get --assume-yes update
    - name: install build dependencies
      run: sudo apt-get --assume-yes install bison flex
    - name: configure 
      run: ./configure --target=h8300-hitachi-hms --prefix=/usr --exec_prefix=h8300-hms-cil --disable-nls
    - name: make
      run: make
    - name: make install
      run: make install
