name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install build tools
      run: sudo apt-get install bison flex
    - name: configure 
      run: ./configure --target=h8300-hitachi-hms --prefix=/usr --disable-nls
    - name: make
      run: make
    - name: make install
      run: make install
